### ISSUE TITLE
'Graphics Device initialization failed for :  es2, sw' when trying to run .jar

### ISSUE THREAD

**Issue by johnvictorfs** [RenegadeLucien/project-tenacity#35]
Hello there, i am getting the following issue when trying to execute the latest jar, i am not really good with Java, so i have no clue what that error is honestly, i am on Ubuntu 19.04 if that matters

```bash
john in ~/Downloads 
❯ java -version                 
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu219.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu219.04.1, mixed mode, sharing)

john in ~/Downloads 
❯ java -jar Project.Tenacity.jar                      
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by RenegadeLucien** [comment]
Do you know what version of GTK (if any) you have on your machine? Apparently [GTK 2.18+ is required to run JavaFX applications](https://stackoverflow.com/questions/21185156/javafx-on-linux-is-showing-a-graphics-device-initialization-failed-for-es2-s) and [there are difficulties involved if you are running GTK 3.](https://stackoverflow.com/questions/21093723/how-to-run-javafx-application-against-gtk-3-libs)

I'm not a Linux user, so I don't know too much about the dependencies for Linux. Sorry =(

**Comment by johnvictorfs** [comment]
I seem to have both versions 2.24.32 and 3.24.8, but i'll look more into that in a few hours, thanks

**Comment by johnvictorfs** [comment]
Couldn't work anything out sadly, the error changed after installing `openjfx` with `sudo apt install openjfx` though

```bash
john in ~/Downloads 
❯ java -jar Project.Tenacity.jar
java.lang.ClassNotFoundException: com.sun.glass.ui.gtk.GtkPlatformFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.glass.ui.PlatformFactory.getPlatformFactory(PlatformFactory.java:42)
	at com.sun.glass.ui.Application.run(Application.java:144)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Failed to load Glass factory class
Exception in thread "main" java.lang.NullPointerException
	at com.sun.glass.ui.Application.run(Application.java:144)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by RenegadeLucien** [comment]
So what I'm going to do is build an earlier version of JavaFX into the next release, which will hopefully make it more compatible with later JDKs. I sort of screwed up by building JavaFX 11 into the current release because I didn't know anyone would need it other than those using the Oracle JDK 11. Several other people using various versions of OpenJDK have also encountered similar issues, so hopefully doing that will fix all of them.

**Comment by johnvictorfs** [comment]
That's nice, really great work you've done on this project, props to you :)

**Comment by RenegadeLucien** [comment]
Alright, so I was actually wrong here in that the Java version mismatch was the issue.

Turns out I'm not building in the correct native libraries (i.e. I'm only building the Windows ones.) So it won't run on Mac or Linux unless you have a suitable JavaFX release on your machine as well.

Tomorrow, when I release, I will also include a version built with the Mac and Linux libraries. Hopefully that works.

**Comment by RenegadeLucien** [comment]
v1.0.1 is out. Try running with the Linux version and let me know how that goes.

**Comment by johnvictorfs** [comment]
Pretty late, haven't received a notification for your last 2 messages for some reason, but i have tried launching the linux version today and it works! Great work :)

**Comment by RenegadeLucien** [comment]
Awesome, thanks =)
